"""modified models

Revision ID: 304f8511effd
Revises: 92b557844006
Create Date: 2026-02-27 05:04:37.871700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '304f8511effd'
down_revision: Union[str, Sequence[str], None] = '92b557844006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('occasion', sa.String(), nullable=True),
    sa.Column('time_of_day', sa.String(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clothing_items', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('clothing_items', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True))
    op.drop_column('clothing_items', 'image_path')
    op.drop_column('clothing_items', 'gender')
    op.drop_column('clothing_items', 'season')
    op.drop_column('clothing_items', 'color')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'skin_tone')
    op.drop_column('users', 'body_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('body_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('skin_tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clothing_items', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clothing_items', sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clothing_items', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clothing_items', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clothing_items', 'embedding')
    op.drop_column('clothing_items', 'image_url')
    op.drop_table('feedback')
    # ### end Alembic commands ###
